plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-sources.cjs

changesetBaseRefs:
  - 'main'
  - 'origin/main'
  - 'upstream/main'
